name: Connect to Netbird
on:
  push:
    branches:
      - main

jobs:
  netbird:
    name: Connect to Netbird
    runs-on: ubuntu-latest
    environment: Raspberry Pi 4
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Netbird Connect
        id: netbird
        uses: Alemiz112/netbird-connect-action@v1
        with:
          setup-key: ${{ secrets.NETBIRD_SETUP_KEY }}
          hostname: 'gh-deploy-ci'
        #   management-url: 'https://my-netbird-management-url.com'
        #   args: '--custom-arg value'
      - run: netbird ssh raspberrypi-1.netbird.cloud
      - run: echo "Hello RP 4!"